name: Continuous Delivery
on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

  bump-version:
    name: "Bump version"
    needs: [setup]
    uses: ./.github/workflows/bump-version.yaml
